import { supabaseAdmin as db } from "@/integrations/supabase/client.server";
import { applySubscription } from "@/lib/billing.server";
const T = process.env.STRIPE_TEST_SECRET_KEY!;
const g = async (p: string) => (await fetch(`https://api.stripe.com/v1${p}`, { headers: { Authorization: `Bearer ${T}` } })).json() as any;
const subs = await g(`/subscriptions?customer=cus_VLrCouKf2R04YI&status=all`);
console.log("subs", subs.data.map((s: any) => [s.status, s.livemode, s.trial_end && new Date(s.trial_end*1000).toISOString().slice(0,10), s.items.data.map((i:any)=>[i.price.unit_amount,i.price.recurring?.interval])]));
const inv = await g(`/invoices?customer=cus_VLrCouKf2R04YI`);
console.log("invoices", inv.data.map((i: any) => [i.status, i.amount_paid, i.currency, i.livemode]));
const before = (await (db as any).from("lender_orgs").select("activated_at,plan_key,subscription_status").eq("id","6893ebf2-7652-4341-958b-f5ec22051019").single()).data;
for (let k=0;k<3;k++) await applySubscription(db, subs.data[0]);
const after = (await (db as any).from("lender_orgs").select("activated_at,plan_key,subscription_status").eq("id","6893ebf2-7652-4341-958b-f5ec22051019").single()).data;
console.log("replay x3 unchanged:", JSON.stringify(before)===JSON.stringify(after), after);
