import { createClient } from "@supabase/supabase-js";
import { factsFromRecord } from "../lib/client-facts.server";
import { buildNarrative, narrativeFactSheet, copyAgreesWithFacts } from "../lib/opportunity-narrative";
import { normalizeAddress } from "../lib/attom.server";

const db = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
const id = "d8ba4d97-f7d2-42b3-9cab-265ac903cca1";
const { data: c } = await db.from("lender_portfolio_clients").select("*").eq("id", id).single();
const key = normalizeAddress([c.address_line1, c.city, [c.state, c.zip].filter(Boolean).join(" ")].filter(Boolean).join(", "));
const { data: intel } = await db.from("property_intel").select("*").eq("address_normalized", key).maybeSingle();
const f = factsFromRecord(c as any, intel);
const { data: opps } = await db.from("homeowner_opportunities").select("category,state").eq("portfolio_client_id", id);
const cats = [...new Set((opps ?? []).filter((o:any)=>o.state==="open").map((o:any)=>o.category))];
const n = buildNarrative({ role: "agent", facts: f, categories: cats, firstName: "Kevin" });
const { data: cached } = await db.from("opportunity_actions").select("audience,draft_subject,draft_body").eq("client_id", id).limit(5);
console.log("CATEGORIES", cats);
console.log("FACTS", JSON.stringify({value:f.value,loanBalance:f.loanBalance,equityDollars:f.equityDollars,equityPct:f.equityPct,ltvPct:f.ltvPct,ratePct:f.ratePct,tenureYears:f.tenureYears,beds:f.beds,baths:f.baths,sqft:f.sqft,equityActionable:f.equityActionable},null,2));
console.log("SHEET", narrativeFactSheet(f));
console.log("NARRATIVE", JSON.stringify(n,null,2));
console.log("CACHED DRAFTS", JSON.stringify(cached,null,2));
for (const d of cached ?? []) console.log("cached valid?", d.audience, copyAgreesWithFacts(`${d.draft_subject} ${d.draft_body}`, f, d.audience==="agent"?"agent":"lender"));
