import { createClient } from "@supabase/supabase-js";
import { factsFromRecord } from "../lib/client-facts.server";
import { buildNarrative } from "../lib/opportunity-narrative";
import { normalizeAddress } from "../lib/attom.server";
const db = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
const { data: c } = await db.from("lender_portfolio_clients").select("*").eq("id","d8ba4d97-f7d2-42b3-9cab-265ac903cca1").single();
const key = normalizeAddress([c.address_line1, c.city, [c.state, c.zip].filter(Boolean).join(" ")].join(", "));
const { data: intel } = await db.from("property_intel").select("*").eq("address_normalized", key).maybeSingle();
const f = factsFromRecord(c as any, intel);
const n = buildNarrative({ role: "agent", facts: f, categories: ["equity","heloc","move_up","investment"], firstName: "Kevin" });
console.log([n.headline,n.whyNow,n.whyItMatters,...n.supportingSignals.map(s=>`• ${s}`),...n.secondarySignals.map(s=>`• ${s}`),n.openerSeed].join("\n"));
