/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLenderRouteRouteImport } from './routes/_authenticated/lender/route'
import { Route as AuthenticatedLenderIndexRouteImport } from './routes/_authenticated/lender/index'
import { Route as ApiPublicLeadsTickRouteImport } from './routes/api/public/leads.tick'
import { Route as ApiPublicGhlDrainRouteImport } from './routes/api/public/ghl.drain'
import { Route as ApiPublicFelloWebhookRouteImport } from './routes/api/public/fello.webhook'
import { Route as AuthenticatedLenderPortfolioIdRouteImport } from './routes/_authenticated/lender/portfolio.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLenderRouteRoute =
  AuthenticatedLenderRouteRouteImport.update({
    id: '/lender',
    path: '/lender',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLenderIndexRoute =
  AuthenticatedLenderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLenderRouteRoute,
  } as any)
const ApiPublicLeadsTickRoute = ApiPublicLeadsTickRouteImport.update({
  id: '/api/public/leads/tick',
  path: '/api/public/leads/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGhlDrainRoute = ApiPublicGhlDrainRouteImport.update({
  id: '/api/public/ghl/drain',
  path: '/api/public/ghl/drain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFelloWebhookRoute = ApiPublicFelloWebhookRouteImport.update({
  id: '/api/public/fello/webhook',
  path: '/api/public/fello/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLenderPortfolioIdRoute =
  AuthenticatedLenderPortfolioIdRouteImport.update({
    id: '/portfolio/$id',
    path: '/portfolio/$id',
    getParentRoute: () => AuthenticatedLenderRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/pro': typeof ProRoute
  '/report': typeof ReportRoute
  '/request': typeof RequestRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lender': typeof AuthenticatedLenderRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lender/': typeof AuthenticatedLenderIndexRoute
  '/lender/portfolio/$id': typeof AuthenticatedLenderPortfolioIdRoute
  '/api/public/fello/webhook': typeof ApiPublicFelloWebhookRoute
  '/api/public/ghl/drain': typeof ApiPublicGhlDrainRoute
  '/api/public/leads/tick': typeof ApiPublicLeadsTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/pro': typeof ProRoute
  '/report': typeof ReportRoute
  '/request': typeof RequestRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lender': typeof AuthenticatedLenderIndexRoute
  '/lender/portfolio/$id': typeof AuthenticatedLenderPortfolioIdRoute
  '/api/public/fello/webhook': typeof ApiPublicFelloWebhookRoute
  '/api/public/ghl/drain': typeof ApiPublicGhlDrainRoute
  '/api/public/leads/tick': typeof ApiPublicLeadsTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/pro': typeof ProRoute
  '/report': typeof ReportRoute
  '/request': typeof RequestRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/lender': typeof AuthenticatedLenderRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lender/': typeof AuthenticatedLenderIndexRoute
  '/_authenticated/lender/portfolio/$id': typeof AuthenticatedLenderPortfolioIdRoute
  '/api/public/fello/webhook': typeof ApiPublicFelloWebhookRoute
  '/api/public/ghl/drain': typeof ApiPublicGhlDrainRoute
  '/api/public/leads/tick': typeof ApiPublicLeadsTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/partner'
    | '/pro'
    | '/report'
    | '/request'
    | '/services'
    | '/sitemap.xml'
    | '/lender'
    | '/dashboard'
    | '/lender/'
    | '/lender/portfolio/$id'
    | '/api/public/fello/webhook'
    | '/api/public/ghl/drain'
    | '/api/public/leads/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/partner'
    | '/pro'
    | '/report'
    | '/request'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard'
    | '/lender'
    | '/lender/portfolio/$id'
    | '/api/public/fello/webhook'
    | '/api/public/ghl/drain'
    | '/api/public/leads/tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/partner'
    | '/pro'
    | '/report'
    | '/request'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/lender'
    | '/_authenticated/dashboard'
    | '/_authenticated/lender/'
    | '/_authenticated/lender/portfolio/$id'
    | '/api/public/fello/webhook'
    | '/api/public/ghl/drain'
    | '/api/public/leads/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnerRoute: typeof PartnerRoute
  ProRoute: typeof ProRoute
  ReportRoute: typeof ReportRoute
  RequestRoute: typeof RequestRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicFelloWebhookRoute: typeof ApiPublicFelloWebhookRoute
  ApiPublicGhlDrainRoute: typeof ApiPublicGhlDrainRoute
  ApiPublicLeadsTickRoute: typeof ApiPublicLeadsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lender': {
      id: '/_authenticated/lender'
      path: '/lender'
      fullPath: '/lender'
      preLoaderRoute: typeof AuthenticatedLenderRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lender/': {
      id: '/_authenticated/lender/'
      path: '/'
      fullPath: '/lender/'
      preLoaderRoute: typeof AuthenticatedLenderIndexRouteImport
      parentRoute: typeof AuthenticatedLenderRouteRoute
    }
    '/api/public/leads/tick': {
      id: '/api/public/leads/tick'
      path: '/api/public/leads/tick'
      fullPath: '/api/public/leads/tick'
      preLoaderRoute: typeof ApiPublicLeadsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ghl/drain': {
      id: '/api/public/ghl/drain'
      path: '/api/public/ghl/drain'
      fullPath: '/api/public/ghl/drain'
      preLoaderRoute: typeof ApiPublicGhlDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fello/webhook': {
      id: '/api/public/fello/webhook'
      path: '/api/public/fello/webhook'
      fullPath: '/api/public/fello/webhook'
      preLoaderRoute: typeof ApiPublicFelloWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lender/portfolio/$id': {
      id: '/_authenticated/lender/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/lender/portfolio/$id'
      preLoaderRoute: typeof AuthenticatedLenderPortfolioIdRouteImport
      parentRoute: typeof AuthenticatedLenderRouteRoute
    }
  }
}

interface AuthenticatedLenderRouteRouteChildren {
  AuthenticatedLenderIndexRoute: typeof AuthenticatedLenderIndexRoute
  AuthenticatedLenderPortfolioIdRoute: typeof AuthenticatedLenderPortfolioIdRoute
}

const AuthenticatedLenderRouteRouteChildren: AuthenticatedLenderRouteRouteChildren =
  {
    AuthenticatedLenderIndexRoute: AuthenticatedLenderIndexRoute,
    AuthenticatedLenderPortfolioIdRoute: AuthenticatedLenderPortfolioIdRoute,
  }

const AuthenticatedLenderRouteRouteWithChildren =
  AuthenticatedLenderRouteRoute._addFileChildren(
    AuthenticatedLenderRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLenderRouteRoute: typeof AuthenticatedLenderRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLenderRouteRoute: AuthenticatedLenderRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PartnerRoute: PartnerRoute,
  ProRoute: ProRoute,
  ReportRoute: ReportRoute,
  RequestRoute: RequestRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicFelloWebhookRoute: ApiPublicFelloWebhookRoute,
  ApiPublicGhlDrainRoute: ApiPublicGhlDrainRoute,
  ApiPublicLeadsTickRoute: ApiPublicLeadsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
