/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedLenderRouteRouteImport } from './routes/_authenticated/lender/route'
import { Route as AuthenticatedAgentRouteRouteImport } from './routes/_authenticated/agent/route'
import { Route as AuthenticatedLenderIndexRouteImport } from './routes/_authenticated/lender/index'
import { Route as AuthenticatedAgentIndexRouteImport } from './routes/_authenticated/agent/index'
import { Route as AuthenticatedRequestsIdRouteImport } from './routes/_authenticated/requests.$id'
import { Route as AuthenticatedLenderNetworkRouteImport } from './routes/_authenticated/lender/network'
import { Route as AuthenticatedLenderCampaignsRouteImport } from './routes/_authenticated/lender/campaigns'
import { Route as AuthenticatedAgentCampaignsRouteImport } from './routes/_authenticated/agent/campaigns'
import { Route as ApiPublicLeadsTickRouteImport } from './routes/api/public/leads.tick'
import { Route as ApiPublicGhlDrainRouteImport } from './routes/api/public/ghl.drain'
import { Route as ApiPublicGhlBillingRouteImport } from './routes/api/public/ghl.billing'
import { Route as ApiPublicCampaignsTickRouteImport } from './routes/api/public/campaigns.tick'
import { Route as AuthenticatedLenderPortfolioIdRouteImport } from './routes/_authenticated/lender/portfolio.$id'
import { Route as AuthenticatedAgentPortfolioIdRouteImport } from './routes/_authenticated/agent/portfolio.$id'
import { Route as AuthenticatedLenderPortfolioIdIndexRouteImport } from './routes/_authenticated/lender/portfolio.$id.index'
import { Route as AuthenticatedLenderPortfolioIdImportRouteImport } from './routes/_authenticated/lender/portfolio.$id.import'
import { Route as AuthenticatedLenderPortfolioIdCampaignsRouteImport } from './routes/_authenticated/lender/portfolio.$id.campaigns'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLenderRouteRoute =
  AuthenticatedLenderRouteRouteImport.update({
    id: '/lender',
    path: '/lender',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentRouteRoute = AuthenticatedAgentRouteRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLenderIndexRoute =
  AuthenticatedLenderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLenderRouteRoute,
  } as any)
const AuthenticatedAgentIndexRoute = AuthenticatedAgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAgentRouteRoute,
} as any)
const AuthenticatedRequestsIdRoute = AuthenticatedRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLenderNetworkRoute =
  AuthenticatedLenderNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => AuthenticatedLenderRouteRoute,
  } as any)
const AuthenticatedLenderCampaignsRoute =
  AuthenticatedLenderCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedLenderRouteRoute,
  } as any)
const AuthenticatedAgentCampaignsRoute =
  AuthenticatedAgentCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAgentRouteRoute,
  } as any)
const ApiPublicLeadsTickRoute = ApiPublicLeadsTickRouteImport.update({
  id: '/api/public/leads/tick',
  path: '/api/public/leads/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGhlDrainRoute = ApiPublicGhlDrainRouteImport.update({
  id: '/api/public/ghl/drain',
  path: '/api/public/ghl/drain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGhlBillingRoute = ApiPublicGhlBillingRouteImport.update({
  id: '/api/public/ghl/billing',
  path: '/api/public/ghl/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCampaignsTickRoute = ApiPublicCampaignsTickRouteImport.update({
  id: '/api/public/campaigns/tick',
  path: '/api/public/campaigns/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLenderPortfolioIdRoute =
  AuthenticatedLenderPortfolioIdRouteImport.update({
    id: '/portfolio/$id',
    path: '/portfolio/$id',
    getParentRoute: () => AuthenticatedLenderRouteRoute,
  } as any)
const AuthenticatedAgentPortfolioIdRoute =
  AuthenticatedAgentPortfolioIdRouteImport.update({
    id: '/portfolio/$id',
    path: '/portfolio/$id',
    getParentRoute: () => AuthenticatedAgentRouteRoute,
  } as any)
const AuthenticatedLenderPortfolioIdIndexRoute =
  AuthenticatedLenderPortfolioIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLenderPortfolioIdRoute,
  } as any)
const AuthenticatedLenderPortfolioIdImportRoute =
  AuthenticatedLenderPortfolioIdImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedLenderPortfolioIdRoute,
  } as any)
const AuthenticatedLenderPortfolioIdCampaignsRoute =
  AuthenticatedLenderPortfolioIdCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedLenderPortfolioIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/pro': typeof ProRoute
  '/report': typeof ReportRoute
  '/request': typeof RequestRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agent': typeof AuthenticatedAgentRouteRouteWithChildren
  '/lender': typeof AuthenticatedLenderRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/agent/campaigns': typeof AuthenticatedAgentCampaignsRoute
  '/lender/campaigns': typeof AuthenticatedLenderCampaignsRoute
  '/lender/network': typeof AuthenticatedLenderNetworkRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/agent/': typeof AuthenticatedAgentIndexRoute
  '/lender/': typeof AuthenticatedLenderIndexRoute
  '/agent/portfolio/$id': typeof AuthenticatedAgentPortfolioIdRoute
  '/lender/portfolio/$id': typeof AuthenticatedLenderPortfolioIdRouteWithChildren
  '/api/public/campaigns/tick': typeof ApiPublicCampaignsTickRoute
  '/api/public/ghl/billing': typeof ApiPublicGhlBillingRoute
  '/api/public/ghl/drain': typeof ApiPublicGhlDrainRoute
  '/api/public/leads/tick': typeof ApiPublicLeadsTickRoute
  '/lender/portfolio/$id/campaigns': typeof AuthenticatedLenderPortfolioIdCampaignsRoute
  '/lender/portfolio/$id/import': typeof AuthenticatedLenderPortfolioIdImportRoute
  '/lender/portfolio/$id/': typeof AuthenticatedLenderPortfolioIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/pro': typeof ProRoute
  '/report': typeof ReportRoute
  '/request': typeof RequestRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/agent/campaigns': typeof AuthenticatedAgentCampaignsRoute
  '/lender/campaigns': typeof AuthenticatedLenderCampaignsRoute
  '/lender/network': typeof AuthenticatedLenderNetworkRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/agent': typeof AuthenticatedAgentIndexRoute
  '/lender': typeof AuthenticatedLenderIndexRoute
  '/agent/portfolio/$id': typeof AuthenticatedAgentPortfolioIdRoute
  '/api/public/campaigns/tick': typeof ApiPublicCampaignsTickRoute
  '/api/public/ghl/billing': typeof ApiPublicGhlBillingRoute
  '/api/public/ghl/drain': typeof ApiPublicGhlDrainRoute
  '/api/public/leads/tick': typeof ApiPublicLeadsTickRoute
  '/lender/portfolio/$id/campaigns': typeof AuthenticatedLenderPortfolioIdCampaignsRoute
  '/lender/portfolio/$id/import': typeof AuthenticatedLenderPortfolioIdImportRoute
  '/lender/portfolio/$id': typeof AuthenticatedLenderPortfolioIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/pro': typeof ProRoute
  '/report': typeof ReportRoute
  '/request': typeof RequestRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRouteRouteWithChildren
  '/_authenticated/lender': typeof AuthenticatedLenderRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/agent/campaigns': typeof AuthenticatedAgentCampaignsRoute
  '/_authenticated/lender/campaigns': typeof AuthenticatedLenderCampaignsRoute
  '/_authenticated/lender/network': typeof AuthenticatedLenderNetworkRoute
  '/_authenticated/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/_authenticated/agent/': typeof AuthenticatedAgentIndexRoute
  '/_authenticated/lender/': typeof AuthenticatedLenderIndexRoute
  '/_authenticated/agent/portfolio/$id': typeof AuthenticatedAgentPortfolioIdRoute
  '/_authenticated/lender/portfolio/$id': typeof AuthenticatedLenderPortfolioIdRouteWithChildren
  '/api/public/campaigns/tick': typeof ApiPublicCampaignsTickRoute
  '/api/public/ghl/billing': typeof ApiPublicGhlBillingRoute
  '/api/public/ghl/drain': typeof ApiPublicGhlDrainRoute
  '/api/public/leads/tick': typeof ApiPublicLeadsTickRoute
  '/_authenticated/lender/portfolio/$id/campaigns': typeof AuthenticatedLenderPortfolioIdCampaignsRoute
  '/_authenticated/lender/portfolio/$id/import': typeof AuthenticatedLenderPortfolioIdImportRoute
  '/_authenticated/lender/portfolio/$id/': typeof AuthenticatedLenderPortfolioIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/partner'
    | '/pro'
    | '/report'
    | '/request'
    | '/services'
    | '/sitemap.xml'
    | '/agent'
    | '/lender'
    | '/admin'
    | '/dashboard'
    | '/agent/campaigns'
    | '/lender/campaigns'
    | '/lender/network'
    | '/requests/$id'
    | '/agent/'
    | '/lender/'
    | '/agent/portfolio/$id'
    | '/lender/portfolio/$id'
    | '/api/public/campaigns/tick'
    | '/api/public/ghl/billing'
    | '/api/public/ghl/drain'
    | '/api/public/leads/tick'
    | '/lender/portfolio/$id/campaigns'
    | '/lender/portfolio/$id/import'
    | '/lender/portfolio/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/partner'
    | '/pro'
    | '/report'
    | '/request'
    | '/services'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/agent/campaigns'
    | '/lender/campaigns'
    | '/lender/network'
    | '/requests/$id'
    | '/agent'
    | '/lender'
    | '/agent/portfolio/$id'
    | '/api/public/campaigns/tick'
    | '/api/public/ghl/billing'
    | '/api/public/ghl/drain'
    | '/api/public/leads/tick'
    | '/lender/portfolio/$id/campaigns'
    | '/lender/portfolio/$id/import'
    | '/lender/portfolio/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/partner'
    | '/pro'
    | '/report'
    | '/request'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/agent'
    | '/_authenticated/lender'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/agent/campaigns'
    | '/_authenticated/lender/campaigns'
    | '/_authenticated/lender/network'
    | '/_authenticated/requests/$id'
    | '/_authenticated/agent/'
    | '/_authenticated/lender/'
    | '/_authenticated/agent/portfolio/$id'
    | '/_authenticated/lender/portfolio/$id'
    | '/api/public/campaigns/tick'
    | '/api/public/ghl/billing'
    | '/api/public/ghl/drain'
    | '/api/public/leads/tick'
    | '/_authenticated/lender/portfolio/$id/campaigns'
    | '/_authenticated/lender/portfolio/$id/import'
    | '/_authenticated/lender/portfolio/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnerRoute: typeof PartnerRoute
  ProRoute: typeof ProRoute
  ReportRoute: typeof ReportRoute
  RequestRoute: typeof RequestRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicCampaignsTickRoute: typeof ApiPublicCampaignsTickRoute
  ApiPublicGhlBillingRoute: typeof ApiPublicGhlBillingRoute
  ApiPublicGhlDrainRoute: typeof ApiPublicGhlDrainRoute
  ApiPublicLeadsTickRoute: typeof ApiPublicLeadsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lender': {
      id: '/_authenticated/lender'
      path: '/lender'
      fullPath: '/lender'
      preLoaderRoute: typeof AuthenticatedLenderRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lender/': {
      id: '/_authenticated/lender/'
      path: '/'
      fullPath: '/lender/'
      preLoaderRoute: typeof AuthenticatedLenderIndexRouteImport
      parentRoute: typeof AuthenticatedLenderRouteRoute
    }
    '/_authenticated/agent/': {
      id: '/_authenticated/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AuthenticatedAgentIndexRouteImport
      parentRoute: typeof AuthenticatedAgentRouteRoute
    }
    '/_authenticated/requests/$id': {
      id: '/_authenticated/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof AuthenticatedRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lender/network': {
      id: '/_authenticated/lender/network'
      path: '/network'
      fullPath: '/lender/network'
      preLoaderRoute: typeof AuthenticatedLenderNetworkRouteImport
      parentRoute: typeof AuthenticatedLenderRouteRoute
    }
    '/_authenticated/lender/campaigns': {
      id: '/_authenticated/lender/campaigns'
      path: '/campaigns'
      fullPath: '/lender/campaigns'
      preLoaderRoute: typeof AuthenticatedLenderCampaignsRouteImport
      parentRoute: typeof AuthenticatedLenderRouteRoute
    }
    '/_authenticated/agent/campaigns': {
      id: '/_authenticated/agent/campaigns'
      path: '/campaigns'
      fullPath: '/agent/campaigns'
      preLoaderRoute: typeof AuthenticatedAgentCampaignsRouteImport
      parentRoute: typeof AuthenticatedAgentRouteRoute
    }
    '/api/public/leads/tick': {
      id: '/api/public/leads/tick'
      path: '/api/public/leads/tick'
      fullPath: '/api/public/leads/tick'
      preLoaderRoute: typeof ApiPublicLeadsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ghl/drain': {
      id: '/api/public/ghl/drain'
      path: '/api/public/ghl/drain'
      fullPath: '/api/public/ghl/drain'
      preLoaderRoute: typeof ApiPublicGhlDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ghl/billing': {
      id: '/api/public/ghl/billing'
      path: '/api/public/ghl/billing'
      fullPath: '/api/public/ghl/billing'
      preLoaderRoute: typeof ApiPublicGhlBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/campaigns/tick': {
      id: '/api/public/campaigns/tick'
      path: '/api/public/campaigns/tick'
      fullPath: '/api/public/campaigns/tick'
      preLoaderRoute: typeof ApiPublicCampaignsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lender/portfolio/$id': {
      id: '/_authenticated/lender/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/lender/portfolio/$id'
      preLoaderRoute: typeof AuthenticatedLenderPortfolioIdRouteImport
      parentRoute: typeof AuthenticatedLenderRouteRoute
    }
    '/_authenticated/agent/portfolio/$id': {
      id: '/_authenticated/agent/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/agent/portfolio/$id'
      preLoaderRoute: typeof AuthenticatedAgentPortfolioIdRouteImport
      parentRoute: typeof AuthenticatedAgentRouteRoute
    }
    '/_authenticated/lender/portfolio/$id/': {
      id: '/_authenticated/lender/portfolio/$id/'
      path: '/'
      fullPath: '/lender/portfolio/$id/'
      preLoaderRoute: typeof AuthenticatedLenderPortfolioIdIndexRouteImport
      parentRoute: typeof AuthenticatedLenderPortfolioIdRoute
    }
    '/_authenticated/lender/portfolio/$id/import': {
      id: '/_authenticated/lender/portfolio/$id/import'
      path: '/import'
      fullPath: '/lender/portfolio/$id/import'
      preLoaderRoute: typeof AuthenticatedLenderPortfolioIdImportRouteImport
      parentRoute: typeof AuthenticatedLenderPortfolioIdRoute
    }
    '/_authenticated/lender/portfolio/$id/campaigns': {
      id: '/_authenticated/lender/portfolio/$id/campaigns'
      path: '/campaigns'
      fullPath: '/lender/portfolio/$id/campaigns'
      preLoaderRoute: typeof AuthenticatedLenderPortfolioIdCampaignsRouteImport
      parentRoute: typeof AuthenticatedLenderPortfolioIdRoute
    }
  }
}

interface AuthenticatedAgentRouteRouteChildren {
  AuthenticatedAgentCampaignsRoute: typeof AuthenticatedAgentCampaignsRoute
  AuthenticatedAgentIndexRoute: typeof AuthenticatedAgentIndexRoute
  AuthenticatedAgentPortfolioIdRoute: typeof AuthenticatedAgentPortfolioIdRoute
}

const AuthenticatedAgentRouteRouteChildren: AuthenticatedAgentRouteRouteChildren =
  {
    AuthenticatedAgentCampaignsRoute: AuthenticatedAgentCampaignsRoute,
    AuthenticatedAgentIndexRoute: AuthenticatedAgentIndexRoute,
    AuthenticatedAgentPortfolioIdRoute: AuthenticatedAgentPortfolioIdRoute,
  }

const AuthenticatedAgentRouteRouteWithChildren =
  AuthenticatedAgentRouteRoute._addFileChildren(
    AuthenticatedAgentRouteRouteChildren,
  )

interface AuthenticatedLenderPortfolioIdRouteChildren {
  AuthenticatedLenderPortfolioIdCampaignsRoute: typeof AuthenticatedLenderPortfolioIdCampaignsRoute
  AuthenticatedLenderPortfolioIdImportRoute: typeof AuthenticatedLenderPortfolioIdImportRoute
  AuthenticatedLenderPortfolioIdIndexRoute: typeof AuthenticatedLenderPortfolioIdIndexRoute
}

const AuthenticatedLenderPortfolioIdRouteChildren: AuthenticatedLenderPortfolioIdRouteChildren =
  {
    AuthenticatedLenderPortfolioIdCampaignsRoute:
      AuthenticatedLenderPortfolioIdCampaignsRoute,
    AuthenticatedLenderPortfolioIdImportRoute:
      AuthenticatedLenderPortfolioIdImportRoute,
    AuthenticatedLenderPortfolioIdIndexRoute:
      AuthenticatedLenderPortfolioIdIndexRoute,
  }

const AuthenticatedLenderPortfolioIdRouteWithChildren =
  AuthenticatedLenderPortfolioIdRoute._addFileChildren(
    AuthenticatedLenderPortfolioIdRouteChildren,
  )

interface AuthenticatedLenderRouteRouteChildren {
  AuthenticatedLenderCampaignsRoute: typeof AuthenticatedLenderCampaignsRoute
  AuthenticatedLenderNetworkRoute: typeof AuthenticatedLenderNetworkRoute
  AuthenticatedLenderIndexRoute: typeof AuthenticatedLenderIndexRoute
  AuthenticatedLenderPortfolioIdRoute: typeof AuthenticatedLenderPortfolioIdRouteWithChildren
}

const AuthenticatedLenderRouteRouteChildren: AuthenticatedLenderRouteRouteChildren =
  {
    AuthenticatedLenderCampaignsRoute: AuthenticatedLenderCampaignsRoute,
    AuthenticatedLenderNetworkRoute: AuthenticatedLenderNetworkRoute,
    AuthenticatedLenderIndexRoute: AuthenticatedLenderIndexRoute,
    AuthenticatedLenderPortfolioIdRoute:
      AuthenticatedLenderPortfolioIdRouteWithChildren,
  }

const AuthenticatedLenderRouteRouteWithChildren =
  AuthenticatedLenderRouteRoute._addFileChildren(
    AuthenticatedLenderRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentRouteRoute: typeof AuthenticatedAgentRouteRouteWithChildren
  AuthenticatedLenderRouteRoute: typeof AuthenticatedLenderRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRequestsIdRoute: typeof AuthenticatedRequestsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentRouteRoute: AuthenticatedAgentRouteRouteWithChildren,
  AuthenticatedLenderRouteRoute: AuthenticatedLenderRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRequestsIdRoute: AuthenticatedRequestsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PartnerRoute: PartnerRoute,
  ProRoute: ProRoute,
  ReportRoute: ReportRoute,
  RequestRoute: RequestRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicCampaignsTickRoute: ApiPublicCampaignsTickRoute,
  ApiPublicGhlBillingRoute: ApiPublicGhlBillingRoute,
  ApiPublicGhlDrainRoute: ApiPublicGhlDrainRoute,
  ApiPublicLeadsTickRoute: ApiPublicLeadsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
